# Generated by Django 2.2.2 on 2019-06-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190629_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb2',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
