# Generated by Django 2.2.2 on 2019-06-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_thumb2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb2',
            field=models.ImageField(blank=True, default='default2.png', upload_to=''),
        ),
    ]
