# Generated by Django 2.2.2 on 2019-06-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190629_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb3',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb2',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
